# Generated by Django 4.2.7 on 2026-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_arabe', models.CharField(blank=True, max_length=100)),
                ('saison', models.CharField(max_length=50)),
                ('mois_debut', models.IntegerField()),
                ('mois_fin', models.IntegerField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('pluie_min', models.FloatField()),
                ('pluie_max', models.FloatField()),
                ('type_sol', models.CharField(max_length=100)),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
